"""update location table

Revision ID: 94288a3a5d20
Revises: ff1779fcbe00
Create Date: 2024-05-01 22:36:18.954627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94288a3a5d20'
down_revision = 'ff1779fcbe00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.alter_column('Office',
               existing_type=sa.BOOLEAN(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.drop_column('Extra')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Extra', sa.BOOLEAN(), nullable=False))
        batch_op.alter_column('Office',
               existing_type=sa.Integer(),
               type_=sa.BOOLEAN(),
               existing_nullable=False)

    # ### end Alembic commands ###
